dry-rb/dry-logic

spec/spec_helper.rb

I noticed that when I just type `rspec` or `rake` in a shell to run the tests of this gem, it fails because `spec_helper.rb` uses `Pathname`, which is undefined.  This just adds the line `require 'pathname'` to fix that.  Thanks!

spec_helper.rb: Add a require for 'pathname'

---

README.md

`dry-data` has been renamed to `dry-types` but the readme for `dry-logic` still references old name (resulting in Github's 404)

dry-data -> dry-types

---

lib/dry/logic/predicates.rb
spec/unit/predicates/even_spec.rb
spec/unit/predicates/number_spec.rb
spec/unit/predicates/odd_spec.rb

Fixes #5.
Jury is out on the `:number?`  predicate.
It appears to be quicker to test if ruby can float a string than match a regex. 
The downside is that this doesn't cover the edge cases that the regexps in coercible do, and you have rescue potential errors.
What are your thoughts @solnic. Happy to revise.
```
require "benchmark"
Benchmark.bm(7) do |x|
x.report("float_conversion:") { (1..10000).each { |i| Float(Random.new.rand(i).to_s) } }
x.report("regex_conversion:") { (1..10000).each { |i| Regexp.new(/\A[+-]?\d+\Z/).match(Random.new.rand(i).to_s) } }
end
user       system     total    real
float_conversion:  0.100000   0.070000   0.170000 (  0.169644)
regex_conversion:  0.200000   0.080000   0.280000 (  0.279153)
```

Add numerically predicates.

---

lib/dry/logic/predicates.rb
spec/unit/predicates/excluded_from_spec.rb
spec/unit/predicates/excludes_spec.rb
spec/unit/predicates/included_in_spec.rb
spec/unit/predicates/includes_spec.rb

Added the new predicates & converted the current `exclusion?` predicate
to avoid having to navigate the predicate_set for performance reasons.
TODO: Confirm naming of predicates

Add includes? and excludes? predicates, rename inclusion? and exclusion?

---

.travis.yml
lib/dry/logic/predicates.rb
spec/unit/predicates/excludes_spec.rb
spec/unit/predicates/includes_spec.rb

If includes is called on an input that supports the method then call
it, otherwise return false.
If we encounter a type error (e.g. String.include?(Integer) ) then also
return false.
Due to the enhanced complexity of the predicate lets make excludes?
simply be its opposite.
Fixes https://github.com/dry-rb/dry-logic/issues/10

Minimise errors when using includes & excludes

---

lib/dry/logic/predicate.rb
spec/shared/predicates.rb
spec/unit/predicate_spec.rb

1) update shared specs to work with predicates where airity != 2
2) capture predicate args without currying the function to maintain
airity and parameters
3) add specs for access to predicate airity & parameters
3) raise errors when calling a predicate with invalid no. args.

improvements to predicate handling

---

lib/dry/logic/predicate.rb
spec/unit/predicate_spec.rb
spec/unit/rule/value_spec.rb

This change will enable us to support predicates without any args.
Any args that are curried take president over those that are passed
into the call

Enable predicates that don't need input

---

lib/dry/logic/predicates.rb

call methods directly instead of using self[]

---

.codeclimate.yml
.travis.yml
Gemfile
spec/spec_helper.rb

* Run coverage only after successful first job (TRAVIS_JOB_NUMBER=X.1)
* Test on rbx-3
* Update codeclimate (https://github.com/codeclimate/ruby-test-reporter#upgrading-from-pre-10-versions)

Update CI config

---

lib/dry/logic/predicates.rb

Handle deprecation warnings for `Fixnum` in ruby 2.4.0 by doing a simple check before accessing the constant.

handle deprecation warnings for Fixnum in ruby 2.4.0

---

lib/dry/logic/rule.rb
spec/unit/rule_spec.rb

@solnic ping me if you have any comments on this, this allows for passing injected deps into externally defined predicates
example code from dry-v
```ruby
module IssuesPredicate
include Dry::Logic::Predicates
predicate(:equipment_exists?) do |account, value|
account.include?(value)
end
end
Schema = Dry::Validation.Schema do
configure do
option :account
predicates(::IssuesPredicate)
end
optional(:equipment_ids).each { equipment_exists?(account) }
end
```
/cc @NikitaNaumenko

Fix instance_of? checks called on schema instance in dry-v

---

lib/dry/logic/operations/negation.rb
spec/unit/operations/negation_spec.rb

* Fix inconsistency when #call calls []
* Add [] method to prevent errors when it's required, e.g. with And
I didn't find the specific issue, but this PR fixes usages of negation like
* Using negation inside of And or another operations when calling method `[]` (I used double negation for test)
* Calling `not` on `schema` in `dry-validation`(this probably needs also adding `[]` for schemas)
* Inconsistency between `call` and `[]`, i.e. all `call` methods use `call` and `[]` methods use `[]` which is not the case for Negation

Fix Operations::Negation issues.

---

lib/dry/logic/predicates.rb
spec/shared/predicates.rb
spec/unit/operations/or_spec.rb
spec/unit/predicates/none_spec.rb

Originally, dry-validation couldn't use `nil?` because it was defined on `Object`, now it's possible as DSL objects use `BasicObject` or they undef methods that are in conflict with the DSL.

Add nil? and make none? an alias for backward compat

---

lib/dry/logic/predicates.rb
spec/unit/predicates/respond_to_spec.rb

This is part of a feature for `dry-types` about being able to define a type by a contract of implemented methods in the value.
Calling the predicate method `respond_to?` has the undesired side effect of obfuscating `Object#respond_to?` in `Dry::Logic::Predicates`. An alternative would be to name it `responds_to?`, but it would be less intuitive for users who would find more natural to have the predicate named like the method. Another solution would be to decouple predicate names from `Dry::Logic::Predicates` method names. What do you think?
**Resources**
- [Original discussion](https://discourse.dry-rb.org/t/support-for-type-classes/759)

Add respond_to? predicate

---

lib/dry/logic/predicates.rb
spec/unit/predicates/respond_to_spec.rb

This is the order that `dry-types` expect, and it makes more sense
having function currying in mind
@solnic this should be merged to master. It was my mistake yesterday.
References #55

Switch order of arguments in respond_to predicate

---

lib/dry/logic/predicates.rb
spec/unit/predicates/bytesize_spec.rb
spec/unit/predicates/max_bytesize_spec.rb
spec/unit/predicates/min_bytesize_spec.rb

This is a fairly simple enhancement to validate the byteszie of my string input, not just the character count. 
```
irb(main):017:0> 'こ'.size
=> 1
irb(main):018:0> 'こ'.bytesize
=> 3
```
It follows the same form as min_size?, max_size?, and size? predicates. 
For documentation purposes should I open a pr with? https://github.com/dry-rb/dry-rb.org
Follow up: Add integration test to dry-schema

Adding predicates to support min_bytesize? max_bytesize? and bytesize?

---

dry-logic.gemspec

This PR adds 2 URIs to the gemspec:
* `source_code_uri`
* `changelog_uri`

Add metadata to gemspec

---

spec/unit/rule_spec.rb

Here is a small fix which replaces a `fit` with `it`

Remove fit from specs

---

lib/dry/logic/predicates.rb
spec/unit/predicates/format_spec.rb

Ruby 2.7-preview2 raises an error when Regexp#match? receives `nil`, this breaks a few tests in dry-schema. This change in ruby was already reverted but may be re-introduced in the future.
See discussions: https://bugs.ruby-lang.org/issues/13083
This also fixes tests, they were wrong from the beginning.
Finally, it's not recommended to rely on this behavior. The `nil` check may be removed in future major versions, it's only added to make tests in dry-schema pass.

Explicitly support for nil input in format?

---

lib/dry/logic/predicates.rb
spec/unit/predicates/uuid_v4_spec.rb

\A and \z should be used to mark start and end of string.
In other case it will accept strings that for sure are not valid uuids (but include them in one of lines)

correct insecure uuid_v4? predicate regexp

---

docsite/source/operations.html.md

As 6 is not `gt?` (greater than) 6.
Alternatively predicate should be changed to `gteq?`.

Update operations.html.md - invalid result

---

lib/dry/logic/predicates.rb

Fixes dry-rb/dry-schema#290
This resolves the issue with inconsistency in the names of interpolated arguments when using translations for dry-schema/dry-validation messages. Now every interpolated argument is called "num" in all "size" connected validations:
"size?", "min_size?", "max_size?".
This was happening because dry-schema calls `predicate.parameters` and uses them to get names of interpolated args in error messages
Btw wasn't sure if this should be "num" or "size". I chose "num" because it will be backward compatible but on the other hand it's less obvious...

Change argument name in the "size?" method to "num"

---

docsite/source/predicates.html.md
lib/dry/logic/predicates.rb
spec/unit/predicates/uuid_v1_spec.rb
spec/unit/predicates/uuid_v2_spec.rb
spec/unit/predicates/uuid_v3_spec.rb
spec/unit/predicates/uuid_v5_spec.rb

I have a need to validate other versions of UUIDs than just V4. Because the `uuid_v4?` predicate exists, can we also add predicates for other UUID versions?
Should I also add a `uuid?` predicate that checks for V1-V5 UUIDs?
Reference: https://stackoverflow.com/a/38191104

Add predicates for checking V1, V2, V3, V5 UUIDs.

---

spec/unit/predicates/uuid_v1_spec.rb
spec/unit/predicates/uuid_v5_spec.rb

I noticed this morning that some of the comments that I created in https://github.com/dry-rb/dry-logic/pull/75 were incorrect. I have updated these comments.

Fix incorrect comments in uuid_v1_spec and uuid_v5_spec files.

---

changelog.yml
lib/dry/logic/rule/interface.rb
spec/unit/rule_spec.rb

Ruby 3 changed arity of procs made from symbols (because they are lambdas now). This revealed some logic issues (see what I did here). Thanks to this change I finally read the documentation on #arity and required improvements.
P.S. It seems that nobody uses arity < -1 for predicates

Better support for negative arity

---

lib/dry/logic/operations/check.rb
spec/unit/operations/check_spec.rb

When nesting two `Operations::Check` calls
- Ruby 2.7 displays the following warning: `Using the last argument as keyword parameters is deprecated; maybe ** should be added to the call`.
- Ruby 3.0 raises the following error: `undefined method '[]' for nil:NilClass`.
This PR should resolve both problems.

Allow for nested check operations in Ruby 3.0

---

lib/dry/logic/operations/binary.rb

This doesn't really change much but fixes a subtle issue with jruby found in https://github.com/dry-rb/dry-schema/pull/348 It's hard to say whether it's a bug in jruby because it's an intersection of `undef :respond_to?`, `BasicObject` and implicit coercion to keywords. Keywords situation will improve over time so I think jruby shouldn't bother fixing this particular case.

Change arity of binary op constructor

---

docsite/source/predicates.html.md

Small correction in variable name **has_name** to **is_named** on the `Attribute` examples.

Update predicates.html.md documentation

---

lib/dry/logic/predicates.rb
spec/unit/predicates/uri_spec.rb

I use `uri?` predicate to validate whether a string is an valid URI. However, this case fails:
```ruby
schema = Dry::Schema.JSON do
required(:picture_url).filled(:string, uri?: 'https')
end
schema.call(picture_url: '{https://picture.com/some_image.png}')
```
Upon reading code of `URI` module, I notice that `URI::DEFAULT_PARSER.make_regexp` creates a regex that matches only part of the string, and I have no way to avoid that behavior, aside from switching to `URI::RFC3986_Parser::RFC3986_URI`:
```ruby
schema = Dry::Schema.JSON do
required(:picture_url).filled(:string, format?: URI::RFC3986_Parser::RFC3986_URI)
end
```
However, this prevent me from using the nice error message that comes with `uri?` predicate. I suppose some people would have the same problems as me, so I would like to …

Add uri_rfc3986? matcher to support validating full URL

---

lib/dry/logic/predicates.rb
spec/integration/builder/predicate_spec.rb
spec/shared/predicates.rb
spec/unit/operations/check_spec.rb
spec/unit/predicates/is_eql_spec.rb

Deprecate eql? in favor of is_eql?

---

lib/dry/logic/predicates.rb
spec/integration/builder/predicate_spec.rb
spec/unit/predicates/interface_spec.rb

Deprecate respond_to? in favor of interface?

---

lib/dry/logic/predicates.rb
spec/unit/predicates/uuid_v5_spec.rb
spec/unit/predicates/uuid_v6_spec.rb
spec/unit/predicates/uuid_v7_spec.rb
spec/unit/predicates/uuid_v8_spec.rb

While the [updates](https://datatracker.ietf.org/wg/uuidrev/about/) is in a Proposed Standard status, there is already some implementations in the wild and some people (including me) are considering using it in a database for better indexing. Test values taken from the [IETF repository](https://github.com/ietf-wg-uuidrev/rfc4122bis/blob/main/editor-files/draft-peabody-dispatch-new-uuid-format-04.md)

Add predicates for UUIDv6/7/8

---

docsite/source/builder.html.md
docsite/source/operations.html.md
docsite/source/predicates.html.md

Fix some bugs I found in the documentation – Predicates, Operations and Builder sections.

Fix documentation
